### ISSUE TITLE
Some more perla new feedback

### ISSUE THREAD

**Issue by kaeedo** [AngelMunoz/Perla#118]
**Describe the bug**
Running `perla new MyProject -t ff` or `perla new MyProject -id  perla.templates.fable.feliz` causes InvalidOperationException when the command line argument parsing tried to bind the string to an F# string option.

```
 perla new WithId -id perla.templates.fable.feliz
Unhandled exception: System.InvalidOperationException: Cannot parse argument 'perla.templates.fable.feliz' for option '-id' as expected type 'Microsoft.FSharp.Core.FSharpOption`1[System.String]'.
   at System.CommandLine.Binding.ArgumentConverter.GetValueOrDefault[T](ArgumentConversionResult result)
   at System.CommandLine.Parsing.OptionResult.GetValueOrDefault[T]()
   at System.CommandLine.Parsing.SymbolResult.GetValueForOption[T](Option`1 option)
   at System.CommandLine.Parsing.ParseResult.GetValueForOption[T](Option`1 option)
   at FSharp.SystemCommandLine.CommandBuilders.SetHandlerTask@345-5.Invoke(InvocationContext ctx)
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Perla.CliMiddleware.MiddlewareImpl.previewCheck@43-1.MoveNext() in C:\Users\scyth\repos\Perla\src\Perla\CliMiddleware.fs:line 76
   at Perla.CliMiddleware.MiddlewareImpl.esbuildPluginCheck@80-1.MoveNext() in C:\Users\scyth\repos\Perla\src\Perla\CliMiddleware.fs:line 108
   at Perla.CliMiddleware.MiddlewareImpl.templatesCheck@192-1.MoveNext() in C:\Users\scyth\repos\Perla\src\Perla\CliMiddleware.fs:line 197
   at Perla.CliMiddleware.MiddlewareImpl.esbuildBinCheck@156-1.MoveNext() in C:\Users\scyth\repos\Perla\src\Perla\CliMiddleware.fs:line 166
   at Perla.CliMiddleware.MiddlewareImpl.setupCheck@112-1.MoveNext() in C:\Users\scyth\repos\Perla\src\Perla\CliMiddleware.fs:line 121
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**To Reproduce**
Running `perla new MyProject -t ff` or `perla new MyProject -id  perla.templates.fable.feliz`

**Desktop (please complete the following information):**
- .Net 7
 - I've observed this behavior using perla 1.0.0 beta 18 on both windows 10 and linux (fedora 37) 

---

Some additional feedback:

When seeing a list of templates (e.g. after first time setup)
![perlaTemplateList](https://user-images.githubusercontent.com/3847895/232309304-b2742d33-40e5-49dc-9d1c-3acffac459cc.png)
It would be helpful to have the columns to see the shortcut name for it, or the template name as the `-tn` flag expects them. Additionally, the "Belongs to", "parent location", and "last updated at" might not always be useful, and could be hidden behind a `--verbose` flag or similar.

Also. when running template commands that don't reference a specific template, e.g. `perla templates SomeTempalteName -ls table` it would be helpful to not have to include dummy text for template name, as you're just trying to get a list of available templates.

Thanks much again, And if you'd like help with the implementation of this feedback, let me know :)

**Comment by AngelMunoz** [comment]
Oh I didn't expect feedback so soon, less alone a bug report 😂 but I'm very thankful for this, I opened two separate tickets to track these issues individually

> Thanks much again, And if you'd like help with the implementation of this feedback, let me know :)

I'm open to help/provide pointers if you decide to implement these, Just let me know if you intend to give them a try!

**Comment by AngelMunoz** [comment]
Both issues raised from this are closed I'll close this one out as beta 21 should incluide the feedback in this ticket, also thanks for the contribution!
